resolver: lts-13.2
packages:
- ccg
- minipass
- utils
- lambda-calculus
- the-thing

extra-deps:
- git: git@github.com:DexterLB/chatter.git
  commit: 49a52c735f4a01625400830f58b2dab864c75257
- cereal-text-0.1.0.2
- fullstop-0.1.4
- tokenize-0.3.0
- git: git@github.com:DexterLB/HWordNet.git
  commit: 075ef3bbf880ff00b52f50f383510fac9039574e
