name:                lambda-calculus
version:             0.1.0.0
github:              "DexterLB/underpass"
license:             MIT
author:              "dexterlb"
maintainer:          "dexterlb@qtrp.org"
copyright:           "2018 Angel Angelov"

extra-source-files:
- README.md

description:         General lambda-calculus library

dependencies:
- base
- megaparsec
- text
- utils

library:
  source-dirs: src

ghc-options:
- -Wall
- -Werror
- -Wno-orphans

tests:
  lambda-calculus-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lambda-calculus
