name:                minipass
version:             0.1.0.0
github:              "DexterLB/underpass"
license:             MIT
author:              "dexterlb"
maintainer:          "dexterlb@qtrp.org"
copyright:           "2018 Angel Angelov"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/DexterLB/minipass#readme>

dependencies:
- base
- megaparsec
- text
- hashable
- unordered-containers
- mtl
- data-memocombinators

- utils
- lambda-calculus

library:
  source-dirs: src

ghc-options:
- -Wall
- -Werror

executables:
  minipass-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - minipass

tests:
  minipass-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - minipass
