name:                ccg
version:             0.1.0.0
github:              "DexterLB/ccg"
license:             MIT
author:              "dexterlb"
maintainer:          "dexterlb@qtrp.org"
copyright:           "2018 Angel Angelov"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/githubuser/ccg#readme>

dependencies:
- base
- unordered-containers
- hashable
- data-memocombinators
- vector
- text
- utils
- lambda-calculus
- deepseq
- chatter

library:
  source-dirs: src

ghc-options:
- -Wall
- -Werror
- -Wno-orphans

executables:
  ccg-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ccg

tests:
  ccg-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ccg
    - hspec
