name:                utils
version:             0.1.0.0
github:              "DexterLB/underpass"
license:             MIT
author:              "dexterlb"
maintainer:          "dexterlb@qtrp.org"
copyright:           "2018 Angel Angelov"

extra-source-files:
- README.md

description:         General utils library

dependencies:
- base
- megaparsec
- text
- parser-combinators
- unordered-containers
- hashable
- process
- data-memocombinators
- directory

library:
  source-dirs: src

ghc-options:
- -Wall
- -Werror
- -Wno-orphans

tests:
  utils-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - utils
