name:                thething
version:             0.1.0.0
github:              "DexterLB/underpass"
license:             MIT
author:              "dexterlb"
maintainer:          "dexterlb@qtrp.org"
copyright:           "2018 Angel Angelov"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/DexterLB/minipass#readme>

dependencies:
- base
- text
- vector
- deepseq
- hashable
- unordered-containers
- snap-core
- snap-server
- bytestring
- aeson

- lambda-calculus
- utils
- ccg
- minipass

library:
  source-dirs: src

ghc-options:
- -Wall
- -Werror

data-files:
- data/static/*

executables:
  underpass-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - thething

tests:
  thething-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - thething
